# This is a basic workflow to help you get started with Actions

name: Push to Docker and deploy to AKS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker
        uses: azure/docker-login@v1
        with:
          login-server: charles.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set AKS context
        uses: azure/aks-set-context@v1
        with:
          # create with `az ad sp create-for-rbac --sdk-auth`
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ secrets.AZURE_CLUSTER_NAME }}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
      - uses: actions/checkout@v2
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: charles.azurecr.io/${{ secrets.DOCKER_IMAGE_NAME}}:${{ github.sha }}
      - name: Deploy to kubernetes
        run: |
          helm template ./chart --set hostname=${{ secrets.HOSTNAME }} | kubectl apply -f -
